# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nodecomplete
      MYSQL_DATABASE: node-complete
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - mysql-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080

volumes:
  mysql-db:
